version: '3'

services:
  mysql:
    env_file:
      - mysql/mysql.env
    image: mysql:5.5
    volumes:
      - ./resources/:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql

  guacd:
    image: guacamole/guacd:latest

  guacamole:
    env_file:
      - guacamole/guacamole.env
    image: guacamole/guacamole:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - guacd
